version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:6.0
    container_name: file-upload-mongo-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: fileupload
    volumes:
      - mongodb_data_dev:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  # Backend API (development mode)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: file-upload-backend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/fileupload
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=10485760
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - backend_node_modules_dev:/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network
    command: npm run dev

volumes:
  mongodb_data_dev:
    driver: local
  backend_node_modules_dev:
    driver: local

networks:
  app-network:
    driver: bridge
